
;! ========================================================================== !;
;!
;!          ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;!          ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;!          ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;!          ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;!          ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;!          ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;!
;!                                   COLORS
;!
;!                            - Made by Druxorey -
;!                         https://github.com/druxorey
;!
;! ========================================================================== !;

[colors]
alert = #FF5555
background = #121212
border = #44475A
disabled = #525568
foreground = #F8F8F2
primary = #668d7a
secondary = #3d8d66
